name: devfacil_flutter
description: Frontend Flutter para a plataforma DevFacil.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
